export default {
  l_0: 'Operations',
  l_1: 'Create filled documents from selected cells',
  l_2: 'Extract data from filled documents to the sheet',
  l_3: 'Extract data from filled forms to the sheet',
  l_4: 'Get editor access links for documents',
  l_5: 'Select a template document',
  l_6: 'Loading ...',
  l_7: 'Document ID',
  l_8: 'Document folder',
  l_9: 'Select a folder for created documents',
  l_10: 'Unsorted',
  l_11: 'Create a header for data table',
  l_12: 'Type',
  l_13: 'Insert to current sheet horizontally',
  l_14: 'Insert to current sheet vertically',
  l_15: 'Insert to new sheet horizontally',
  l_16: 'Form',
  l_17: 'From',
  l_18: 'New folder name',
  l_19: 'Current timestamp by default',
  l_20: 'Create new folder',
  l_21: 'Select a fill request',
  l_22: 'Fill request ID',
  l_23: 'Select and order filled forms',
  l_24: 'Fill forms from selected area',
  l_25: 'Unknown user',
  l_26: 'Select documents',
  l_27: 'Insert to new sheet vertically',
  l_28: 'Insert header',
  l_29: 'Sort selected documents',
  l_30: 'Create and insert links',
  l_31: 'Set lifetime of links, in days'
};
